name: "Publish to NuGet Gallery"

on: 
  release:
    types: [published]

env:
  PROJECT_PATH: src/NameCase/NameCase/PgbNameCase.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "'https://nuget.org/'"

jobs:
  publish:
    name: "Publish to NuGet Gallery"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        
      - name: "Install Dotnet"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: "Restore packages"
        run: dotnet restore ${{ env.PROJECT_PATH }}
        
      - name: "Build project"
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
        
      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} -p:PackageVersion=${{ github.event.release.name }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name:  "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/<Solution Name>.${{ github.event.release.name }}.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGETPGBNAMECASEKEY }}